name: awesome-lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@d0a68cb29196eafce908de76ec596a7e9ca049da
        with:
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: admin
          profile-region: us-east-1
          async: true
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npx awesome-lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
